config/routes.rb
Unified::Application.routes.draw do

  resources :documents

  resources :promotions

  resources :promotion_payment_statuses

  resources :promotion_categories

  resources :events

  resources :gallery_images

  resources :galleries do
    resources :gallery_images
  end

  root 'spree/home#index'

  resources :team_members

  resources :categories

  resources :documents

  devise_for :users
  
  
  mount Spree::Core::Engine, :at => '/shop'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  comfy_route :cms_admin, :path => '/cms-admin'

  comfy_route :cms, :path => '/cms', :sitemap => false

  resources :posts
  
  Spree::Core::Engine.routes.prepend do
    resources :taxons
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :create, Gallery
    can :read, Gallery
    can :create, GalleryImage
    can :read, GalleryImage
    can :create, Event
    can :read, Event
    can :create, Promotion
    can [:destroy, :update], Gallery, :user_id => user.id
    can [:destroy, :update], GalleryImage, :user_id => user.id
    can [:destroy, :update], Event, :user_id => user.id
    can [:read, :update], Promotion, :user_id => user.id
  end

end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability

  def initialize(user)
    if Role.find(:all, :include=>:admin_users, :conditions => ["admin_users.id = ? AND name = ?", user.id, "Root"]).count > 0
       can :read, Category
       can :manage, Category
       can :read, TeamMember
       can :manage, TeamMember
       can :read, Role
       can :manage, Role
       can :read, User
       can :manage, User
       can :read, AdminUser
       can :manage, AdminUser
       can :read, Promotion
       can :manage, Promotion
       can :read, PromotionCategory
       can :manage, PromotionCategory
       can :read, PromotionPaymentStatus
       can :manage, PromotionPaymentStatus
       can :read, ActiveAdmin::Page, :name => "Store"
    end
    can :read, Attachment
    can :manage, Attachment
    can :read, Gallery
    can :manage, Gallery
    can :read, GalleryImage
    can :manage, GalleryImage
    can :read, Event
    can :manage, Event
    can :read, Post
    can :manage, Post
    can :read, Attachment
    can :manage, Attachment    
    can :read, AdminUser, :id => user.id
    can :manage, AdminUser, :id => user.id
    can :read, ActiveAdmin::Page, :name => "Dashboard"
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_and_belongs_to_many :roles, join_table: 'admin_users_roles', :class_name => 'Role'
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  protected 
    def password_required? 
      false 
    end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :post
  mount_uploader :file, AttachmentUploader
  validates_integrity_of :file
end

app/models/category.rb
class Category < ActiveRecord::Base
     has_many :posts
     mount_uploader :image, ImageUploader   
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :promotion
  mount_uploader :file, DocumentUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
     belongs_to :country, :class_name => 'Spree::Country'
     belongs_to :user
     has_many :gallery_images
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  belongs_to :gallery
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
        has_many :attachments
        belongs_to :category
        belongs_to :product_range, :class_name => 'Spree::Taxonomy'
        accepts_nested_attributes_for :attachments, allow_destroy: true
        mount_uploader :image, ImageUploader  
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :region, :class_name => 'Spree::Country'
  belongs_to :brand, :class_name => 'Spree::Taxonomy'
  #has_one :currency, :class_name => 'Money::Currency::table' 
  belongs_to :promotion_category
  belongs_to :promotion_payment_status
  has_many :documents, :dependent => :destroy
  belongs_to :user
  accepts_nested_attributes_for :documents
  #before_create :make_processing
  after_save :notify_admins
  
  def documents_for_form
    collection = documents.where(promotion_id: id)
    collection.any? ? collection : documents.build
  end 
  
  def make_processing
    self.promotion_payment_status = PromotionPaymentStatus.find(2)
  end
  
  def notify_admins
     ActionMailer::Base.perform_deliveries = true
     ActionMailer::Base.raise_delivery_errors = true
     UserMailer.promotion_notification(self).deliver
  end
end

app/models/promotion_category.rb
class PromotionCategory < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admin_users
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
        mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :product_ranges, join_table: 'product_ranges_users', :class_name => 'Spree::Taxonomy'
  belongs_to :address, :class_name => 'Spree::Address'
  accepts_nested_attributes_for :address,  :allow_destroy => true
  has_and_belongs_to_many :spree_roles, join_table: 'spree_roles_users', :class_name => 'Spree::Role'
  has_many :spree_orders, :class_name => 'Spree::Order'
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :registerable
  
  def has_spree_role? (role)
      spree_roles.where(name: role).length > 0
  end
  
  def last_incomplete_spree_order
      spree_orders.where.not(state: 'complete').order("updated_at").last
  end
  
  # Getter
  def name
    [first_name, last_name].join(' ')
  end

  protected 
    def password_required? 
      false 
    end
  
end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < InheritedResources::Base

  before_action :set_gallery_image, only: [:show, :edit, :update, :destroy]
  
  def index
     @gallery = Gallery.find(params[:gallery_id])
     @gallery_images = @gallery.gallery_images.page(params[:page]).per(2)
  end

  def create
    @gallery_image = GalleryImage.new(gallery_image_params)
    #@gallery_image.gallery = Gallery.find(params[:gallery_id])
    respond_to do |format|
      if @gallery_image.save
        format.html { redirect_to @gallery_image, notice: 'Gallery Image was successfully added.' }
        format.json { render action: 'show', status: :created, location: @gallery_image }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    
    respond_to do |format|
      if @gallery_image.update(gallery_image_params)
        format.html { redirect_to @gallery_image, notice: 'Gallery Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
      render :layout => "display"
  end 
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery_image
      @gallery_image = GalleryImage.find(params[:id])
    end
  
    def gallery_image_params
      params.require(:gallery_image).permit(:title, :gallery_id, :image, :description, :text)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/gallery_images/_form.html.haml
- if params[:gallery_id].nil? 
  - gallery = @gallery_image.gallery
- else 
  - gallery = Gallery.find(params[:gallery_id])

= form_for @gallery_image, :html => {:multipart => true} do |f|
  - if @gallery_image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gallery_image.errors.count, "error")} prohibited this gallery_image from being saved:"
      %ul
        - @gallery_image.errors.full_messages.each do |msg|
          %li= msg
 
  = f.hidden_field :gallery_id, :value => params[:gallery_id]
  .field
    = f.label :title
    %span{:class => "input_wrapper"}
      = f.text_field :title
  .field
    = f.label :description
    %span{:class => "input_wrapper"}
      = f.text_area :description
  .field
    = f.label :image
    %span{:class => "input_wrapper"}
      = f.file_field :image
  .field
    = f.label :text
    %span{:class => "input_wrapper"}
      = f.text_area :text
  .actions
    %span{:class => "btn_wrapper"}
      = f.submit 'Save'

app/views/gallery_images/edit.html.haml
%h1 
  Editing "
  = @gallery_image.title
  "

= render 'form'

= link_to 'Show', @gallery_image

= link_to 'Back', gallery_images_path

app/views/gallery_images/index.html.haml
- gallery = Gallery.find(params[:gallery_id])
%section{:class => "float_left content_full"}

  #image_view{:style => "display:none;" }
    %iframe{:id => "image_frame", :src => "", :width => 700, :height => 900, :scrolling => "no" }

  %h1= gallery.title
  - if can? :update, gallery
    = link_to 'New Gallery image', new_gallery_gallery_image_path(gallery)
    = " | "
    = link_to 'Edit Gallery', edit_gallery_path(gallery)
  %p= gallery.text
  
  - paginate @gallery_images

  %div{:class => "float_left fifth product_bounds"}

    - @gallery_images.each do |gallery_image|
      %div{:class => "float_left fifth product_fifth"}
        = link_to (image_tag gallery_image.image_url(:thumb)), gallery_image_path(gallery_image), :class => "gallery_image"
        %br
        %h2= link_to gallery_image.title, gallery_image_path(gallery_image), :class => "gallery_image_name"
        - if can? :update, gallery
          = link_to 'Edit', edit_gallery_image_path(gallery_image), :class => "gallery_image_name"
        - if can? :destroy, gallery
          = link_to 'Destroy', gallery_image, :class => "product_name", :method => :delete, :data => { :confirm => 'Are you sure?' }
    

app/views/gallery_images/new.html.haml
- gallery = Gallery.find(params[:gallery_id])

%h1
  New Gallery Image For "
  = gallery.title
  "

= render 'form'

= link_to 'Back', gallery_gallery_images_path(gallery)

app/views/gallery_images/show.html.haml
%h1
  = @gallery_image.title

%p
  %strong Gallery:
  = Gallery.find(@gallery_image.gallery).title
= image_tag @gallery_image.image_url(), :class =>"event_image"
%p
  = @gallery_image.text

- if can? :update, @gallery_image.gallery
  =# link_to 'Edit', edit_gallery_gallery_image_path(@gallery_image.gallery, @gallery_image)
  
=# link_to 'Back', gallery_gallery_images_path(@gallery_image.gallery)