config/routes.rb
Unified::Application.routes.draw do

  resources :documents

  resources :promotions

  resources :promotion_payment_statuses

  resources :promotion_categories

  resources :events

  resources :gallery_images

  resources :galleries do
    resources :gallery_images
  end

  root 'spree/home#index'

  resources :team_members

  resources :categories

  resources :documents

  devise_for :users
  
  
  mount Spree::Core::Engine, :at => '/shop'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  comfy_route :cms_admin, :path => '/cms-admin'

  comfy_route :cms, :path => '/cms', :sitemap => false

  resources :posts
  
  Spree::Core::Engine.routes.prepend do
    resources :taxons
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :create, Gallery
    can :read, Gallery
    can :create, GalleryImage
    can :read, GalleryImage
    can :create, Event
    can :read, Event
    can :create, Promotion
    can [:destroy, :update], Gallery, :user_id => user.id
    can [:destroy, :update], GalleryImage, :user_id => user.id
    can [:destroy, :update], Event, :user_id => user.id
    can [:read, :update], Promotion, :user_id => user.id
  end

end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability

  def initialize(user)
    if Role.find(:all, :include=>:admin_users, :conditions => ["admin_users.id = ? AND name = ?", user.id, "Root"]).count > 0
       can :read, Category
       can :manage, Category
       can :read, TeamMember
       can :manage, TeamMember
       can :read, Role
       can :manage, Role
       can :read, User
       can :manage, User
       can :read, AdminUser
       can :manage, AdminUser
       can :read, Promotion
       can :manage, Promotion
       can :read, PromotionCategory
       can :manage, PromotionCategory
       can :read, PromotionPaymentStatus
       can :manage, PromotionPaymentStatus
       can :read, ActiveAdmin::Page, :name => "Store"
    end
    can :read, Attachment
    can :manage, Attachment
    can :read, Gallery
    can :manage, Gallery
    can :read, GalleryImage
    can :manage, GalleryImage
    can :read, Event
    can :manage, Event
    can :read, Post
    can :manage, Post
    can :read, Attachment
    can :manage, Attachment    
    can :read, AdminUser, :id => user.id
    can :manage, AdminUser, :id => user.id
    can :read, ActiveAdmin::Page, :name => "Dashboard"
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_and_belongs_to_many :roles, join_table: 'admin_users_roles', :class_name => 'Role'
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  protected 
    def password_required? 
      false 
    end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :post
  mount_uploader :file, AttachmentUploader
  validates_integrity_of :file
end

app/models/category.rb
class Category < ActiveRecord::Base
     has_many :posts
     mount_uploader :image, ImageUploader   
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :promotion
  mount_uploader :file, DocumentUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
     belongs_to :country, :class_name => 'Spree::Country'
     belongs_to :user
     has_many :gallery_images
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  belongs_to :gallery
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
        has_many :attachments
        belongs_to :category
        belongs_to :product_range, :class_name => 'Spree::Taxonomy'
        accepts_nested_attributes_for :attachments, allow_destroy: true
        mount_uploader :image, ImageUploader  
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :region, :class_name => 'Spree::Country'
  belongs_to :brand, :class_name => 'Spree::Taxonomy'
  #has_one :currency, :class_name => 'Money::Currency::table' 
  belongs_to :promotion_category
  belongs_to :promotion_payment_status
  has_many :documents, :dependent => :destroy
  belongs_to :user
  accepts_nested_attributes_for :documents
  #before_create :make_processing
  after_save :notify_admins
  
  def documents_for_form
    collection = documents.where(promotion_id: id)
    collection.any? ? collection : documents.build
  end 
  
  def make_processing
    self.promotion_payment_status = PromotionPaymentStatus.find(2)
  end
  
  def notify_admins
     ActionMailer::Base.perform_deliveries = true
     ActionMailer::Base.raise_delivery_errors = true
     UserMailer.promotion_notification(self).deliver
  end
end

app/models/promotion_category.rb
class PromotionCategory < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admin_users
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
        mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :product_ranges, join_table: 'product_ranges_users', :class_name => 'Spree::Taxonomy'
  belongs_to :address, :class_name => 'Spree::Address'
  accepts_nested_attributes_for :address,  :allow_destroy => true
  has_and_belongs_to_many :spree_roles, join_table: 'spree_roles_users', :class_name => 'Spree::Role'
  has_many :spree_orders, :class_name => 'Spree::Order'
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :registerable
  
  def has_spree_role? (role)
      spree_roles.where(name: role).length > 0
  end
  
  def last_incomplete_spree_order
      spree_orders.where.not(state: 'complete').order("updated_at").last
  end
  
  # Getter
  def name
    [first_name, last_name].join(' ')
  end

  protected 
    def password_required? 
      false 
    end
  
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Title
    %th Description
    %th Text
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.title
      %td= category.description
      %td= category.text
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
= link_to @category.title + " > ", category_path(@category)
%br
%br
%h1= @category.title
%div{:class => "category_header"}
  - if !@category.image_url().nil?
    = image_tag(@category.image_url(:thumb).to_s, :class => "post_image")
  %p= @category.text.html_safe
  %br
  %br
  %div{:class => "clear"} <!-- -->
%ul{:class => "category_posts_list"}
  - if params[:taxonomy].nil?
    - posts = @category.posts
  - else
    - taxonomy = params[:taxonomy]
    - posts = Post.where(category: @category, product_range_id: taxonomy) 
  - posts.each do | post |
    - if ProductRangesUser.where(:user_id => current_user, :taxonomy_id => post.product_range).count > 0
      %li
        %div{:class => "category_posts_item"}
          %h2{:class => "category_posts_header"}= post.title
          %div{:class => "category_post_image"}
            = link_to image_tag(post.image_url(:thumb).to_s, :class => "category_posts_images"), post_path(post)
            %div{:class => "clear"} <!-- -->
          - if !post.product_range.nil?
            %p{:align => "justify"}
              %strong Product Range: 
              = post.product_range.name
          = simple_format post.description
          = link_to("More", post_path(post) )
          %div{:class => "clear"} <!-- -->
  %br
  %br
  %br